@startuml
actor Покупатель
participant Кассир
participant Касса
participant БД
activate Покупатель

Покупатель -> Кассир : Запрос желаемого места
activate Кассир
Кассир -> БД : Запрос о свободных местах
activate БД
БД -> Кассир : Ответ о свободных местах
deactivate БД
Кассир -> Покупатель : Ответ о наличии мест
Покупатель -> Кассир : Выбор места
Покупатель -> Кассир : Ввод персональных данных
Кассир -> БД : Ввод данных клиента и билета
activate БД
БД -> Кассир : Ответ о внесении данных
deactivate БД
Покупатель -> Кассир : Оплата
Кассир -> Касса : Ввод суммы
activate Касса
Касса -> Кассир : Ответ о проведении транзакции
deactivate Касса
Кассир -> Покупатель : Выдача билета
deactivate Кассир
deactivate Покупатель
@enduml