@startuml
database БД_Продаж
node Касса <<Интерфейс оплаты>>
node Принтер <<Печать билетов>>
rectangle Приложение {
node Касса_1 <<Приложение кассира>>
node Касса_2 <<Приложение кассира>>
node Касса_3 <<Приложение кассира>>
}

Касса - Приложение
БД_Продаж - Приложение
Принтер - Приложение
@enduml